// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/portfolio": {
    params: {};
  };
  "/portfolio/:slug": {
    params: {
      "slug": string;
    };
  };
  "/about": {
    params: {};
  };
  "/services": {
    params: {};
  };
  "/contact": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/portfolio" | "/portfolio/:slug" | "/about" | "/services" | "/contact";
  };
  "./routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "./routes/portfolio.tsx": {
    id: "routes/portfolio";
    page: "/portfolio";
  };
  "./routes/portfolio.$slug.tsx": {
    id: "routes/portfolio.$slug";
    page: "/portfolio/:slug";
  };
  "./routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "./routes/services.tsx": {
    id: "routes/services";
    page: "/services";
  };
  "./routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/./routes/home.tsx");
  "routes/portfolio": typeof import("./app/./routes/portfolio.tsx");
  "routes/portfolio.$slug": typeof import("./app/./routes/portfolio.$slug.tsx");
  "routes/about": typeof import("./app/./routes/about.tsx");
  "routes/services": typeof import("./app/./routes/services.tsx");
  "routes/contact": typeof import("./app/./routes/contact.tsx");
};